[project]
name = "adopt-a-drain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.0.3",
    "dash-bootstrap-components>=2.0.1",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
]
